# tabspaces = 2

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]
opacity = 1.0
decorations_theme_variant = "Dark"
dynamic_padding = false
decorations = "full"
startup_mode = "Fullscreen"
dynamic_title = true

[scrolling]
history = 10000
multiplier = 3

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font]
size = 16

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[colors.primary]
background = "0x292d3e"
foreground = "0xd0d0d0"

[colors.normal]
black = "0x292d3e"
red = "0xf07178"
green = "0xc3e88d"
yellow = "0xffcb6b"
blue = "0x82aaff"
magenta = "0xc792ea"
cyan = "0x89ddff"
white = "0xd0d0d0"

[colors.bright]
black = "0x434758"
red = "0xff8b92"
green = "0xddffa7"
yellow = "0xffe585"
blue = "0x9cc4ff"
magenta = "0xe1acff"
cyan = "0xa3f7ff"
white = "0xffffff"

[colors]
draw_bold_text_with_bright_colors = true

[bell]
animation = "EaseOutExpo"
duration = 0
color = "#ffffff"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# [mouse.double_click]
# threshold = 300

# [mouse.hints]
# modifiers = "None"

# [mouse.triple_click]
# threshold = 300

[[keyboard.bindings]]
key = "Paste"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
action = "Copy"

[[keyboard.bindings]]
key = "PageUp"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "Shift"
mode = "~Alt"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
mode = "~Alt"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
mode = "~Alt"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "F"
mods = "Control|Shift"
action = "SearchForward"

[[keyboard.bindings]]
key = "B"
mods = "Control|Shift"
action = "SearchBackward"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
mode = "Vi"
action = "ClearSelection"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "PasteSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "NumpadAdd"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "NumpadSubtract"
mods = "Control"
action = "DecreaseFontSize"

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
print_events = false
