local icons = {
  git = " ",
  diagnostics = {
    Error = "✘", --   ✘
    Warn = "󰀪", -- 󰀪 󰳤 󱦄 󱗓 
    Info = "", --    ⁱ 󰋼 󰋽
    Hint = "", --  󰌶 
  },
  status = {
    git = {
      added = "", --  ₊
      modified = "", --  ∗
      removed = "", --  ₋
      branch = "",
      repo = "",
      conflict = "",
      untracked = "󰞋",
      unstaged = "",
      staged = "",
      renamed = "",
      ignored = "",
    },
    diagnostics = {
      error = " ",
      warn = " ",
      info = " ",
      question = "",
      hint = "󰌶 ",
    },
    filename = {
      modified = "+",
      readonly = "🔒",
      zoomed = "🔎",
    },
  },
  -- Default completion kind symbols.
  kinds = {
    Array = "󰅪 ", --  󰅪 󰅨 󱃶
    Boolean = "◩ ", --  ◩ 󰔡 󱃙 󰟡 󰨙 
    Class = "󰌗 ", --  󰌗 󰠱 𝓒
    Color = "󰏘 ", -- 󰸌 󰏘
    Constant = "󰏿 ", --   󰏿
    Constructor = "󰆧 ", --  󰆧   
    Copilot = " ", -- 
    Enum = "󰕘 ", --  󰕘  ℰ 
    EnumMember = " ", --  
    Event = " ", --  
    Field = " ", -- 󰄶  󰆨  󰀻 󰃒
    File = " ", --    󰈔 󰈙
    Folder = " ", --   󰉋
    Function = "󰊕 ", --  󰊕 
    Interface = " ", --    
    Key = " ", -- 
    Keyword = " ", --   󰌋 
    Method = "󰆧 ", --  󰆧 ƒ
    Module = " ", --   󰅩 󰆧 󰏗
    Namespace = " ", --   󰅩
    Null = " ", --  󰟢
    Number = "󰎠 ", --  󰎠 
    Object = " ", --   󰅩
    Operator = "󰃬 ", --  󰃬 󰆕 +
    Package = " ", --   󰏖 󰏗
    Property = "󰖷 ", --  󰜢  
    Reference = "󰈝 ", --  󰈝 󰈇
    Snippet = " ", --  󰘌 ⮡   
    String = "󰅳 ", --  󰅳
    Struct = " ", --   𝓢 󰙅 󱏒
    Text = " ", --   󰉿 𝓐
    TypeParameter = " ", --  󰊄 𝙏
    Unit = " ", --   󰑭 
    Value = " ", --   󰀬 󰎠
    Variable = " ", --   󰀫 
    -- ccls-specific icons.
    TypeAlias = "",
    Parameter = "",
    StaticMethod = "",
    Macro = "",
  },
  documents = {
    Default = "",
    File = "",
    Files = "",
    FileTree = "󰙅",
    Import = "",
    Symlink = "",
  },
  ui = {
    ArrowClosed = "",
    ArrowOpen = "",
    BigCircle = "",
    BigUnfilledCircle = "",
    BookMark = "󰃃",
    Bug = "",
    Calendar = "",
    Check = "󰄳",
    ChevronRight = "",
    Circle = "",
    Close = "󰅖",
    Close_alt = "",
    CloudDownload = "",
    Comment = "󰅺",
    CodeAction = "󰌵",
    Dashboard = "",
    Emoji = "󰱫",
    EmptyFolder = "",
    EmptyFolderOpen = "",
    File = "󰈤",
    Fire = "",
    Folder = "",
    FolderOpen = "",
    Gear = "",
    History = "󰄉",
    Incoming = "󰏷",
    Indicator = "",
    Keyboard = "",
    Left = "",
    List = "",
    Square = "",
    SymlinkFolder = "",
    Lock = "󰍁",
    Modified = "✥",
    Modified_alt = "",
    NewFile = "",
    Newspaper = "",
    Note = "󰍨",
    Outgoing = "󰏻",
    Package = "",
    Pencil = "󰏫",
    Perf = "󰅒",
    Play = "",
    Project = "",
    Right = "",
    RootFolderOpened = "",
    Search = "󰍉",
    Separator = "",
    DoubleSeparator = "󰄾",
    SignIn = "",
    SignOut = "",
    Sort = "",
    Spell = "󰓆",
    Symlink = "",
    Table = "",
    Telescope = "",
  },
  misc = {
    Campass = "󰀹",
    Code = "",
    EscapeST = "",
    Gavel = "",
    Glass = "󰂖",
    PyEnv = "󰌠",
    Squirrel = "",
    Tag = "",
    Tree = "",
    Watch = "",
    Lego = "",
    Vbar = "│",
    Add = "+",
    Added = "",
    Ghost = "󰊠",
    ManUp = "",
    Vim = "",
  },
  dap = {
    Breakpoint = "󰝥",
    BreakpointCondition = "󰟃",
    BreakpointRejected = "",
    LogPoint = "",
    Pause = "",
    Play = "",
    RunLast = "↻",
    StepBack = "",
    StepInto = "󰆹",
    StepOut = "󰆸",
    StepOver = "󰆷",
    Stopped = "",
    Terminate = "󰝤",
  },
}

return icons
